# Python + SQL com SQLite

Neste notebook vamos aprender, de forma simples, como utilizar Python para trabalhar com um banco de dados SQLite.

Vamos aprender a:

- Criar uma conexão com o banco
- Criar um cursor
- Criar uma tabela
- Inserir dados
- Consultar dados
- Excluir dados
- Fechar o cursor
- Fechar a conexão

O fluxo básico será:

Python → Conexão → Cursor → SQL → SQLite

## Importar biblioteca

In [1]:
import sqlite3

## 1. Criando uma conexão

Vamos criar uma conexão com um banco chamado `loja.db`.

Se o arquivo ainda não existir, o SQLite irá criá-lo automaticamente.

In [2]:
conexao = sqlite3.connect("dados/loja.db")

print("Conexão criada com sucesso!")

Conexão criada com sucesso!

## 2. Criando um cursor

O **cursor** é utilizado para executar comandos SQL no banco.

Podemos pensar da seguinte forma:

- `conexao` → comunicação com o banco
- `cursor` → responsável por executar os comandos SQL

In [ ]:
# Criando o cursor
cursor = conexao.cursor()

print("Cursor criado com sucesso!")

Cursor criado com sucesso!

## 3. Criando uma tabela

Agora vamos utilizar SQL para criar uma tabela chamada `produtos`.

A tabela terá:

- `id` → identificador do produto
- `nome` → nome do produto
- `preco` → preço do produto

In [4]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER PRIMARY KEY,
    nome TEXT,
    preco REAL
)
""")

conexao.commit()

print("Tabela criada com sucesso!")

Tabela criada com sucesso!

## 4. Inserindo dados

Agora vamos inserir alguns produtos utilizando o comando SQL `INSERT INTO`.

In [5]:
cursor.execute("""
INSERT INTO produtos (id, nome, preco)
VALUES (1, 'Notebook', 3500)
""")

cursor.execute("""
INSERT INTO produtos (id, nome, preco)
VALUES (2, 'Mouse', 80)
""")

cursor.execute("""
INSERT INTO produtos (id, nome, preco)
VALUES (3, 'Teclado', 150)
""")

conexao.commit()

print("Dados inseridos com sucesso!")

Dados inseridos com sucesso!

## 5. Consultando os dados

Para consultar dados utilizamos o comando SQL `SELECT`.

Primeiro executamos o comando:

```python
cursor.execute()

Depois recuperamos os resultados com:
cursor.fetchall()

In [6]:
cursor.execute("SELECT * FROM produtos")

dados = cursor.fetchall()

print(dados)

[(1, 'Notebook', 3500.0), (2, 'Mouse', 80.0), (3, 'Teclado', 150.0)]

### Visualizando os dados

O resultado de `fetchall()` é uma lista contendo os registros encontrados.

In [7]:
for produto in dados:
    print(produto)

(1, 'Notebook', 3500.0)
(2, 'Mouse', 80.0)
(3, 'Teclado', 150.0)

## 6. Consultando com WHERE

Também podemos utilizar filtros com `WHERE`.

Vamos consultar apenas os produtos com preço maior que 100.

In [9]:
cursor.execute("""
SELECT *
FROM produtos
WHERE preco > 100
ORDER BY preco
""")

dados = cursor.fetchall()

for produto in dados:
    print(produto)

(3, 'Teclado', 150.0)
(1, 'Notebook', 3500.0)

## 7. Excluindo dados

Para excluir dados utilizamos o comando `DELETE`.

Vamos excluir o produto com `id = 2`.

In [10]:
cursor.execute("""
DELETE FROM produtos
WHERE id = 2
""")

conexao.commit()

print("Produto excluído!")

Produto excluído!

Agora vamos consultar novamente a tabela para verificar o resultado.

In [11]:
cursor.execute("SELECT * FROM produtos")

dados = cursor.fetchall()

for produto in dados:
    print(produto)

(1, 'Notebook', 3500.0)
(3, 'Teclado', 150.0)

## 8. Fechando o cursor

Terminamos de utilizar o cursor.

Por isso, podemos fechá-lo:

```python
cursor.close()

In [ ]:
cursor.close()

print("Cursor fechado!")

## 9. Fechando a conexão

Agora também precisamos fechar a conexão com o banco:

```python
conexao.close()

In [ ]:
conexao.close()

## Por que fechar os dois?

Temos dois recursos diferentes, é uma boa prática encerrar os dois.

```text
conexao
   ↓
comunicação com o banco

cursor
   ↓
execução dos comandos SQL
```

# Resumo

O fluxo básico para trabalhar com SQLite utilizando Python é:

```text
1. Importar sqlite3
        ↓
2. Criar conexão
        ↓
3. Criar cursor
        ↓
4. Executar SQL
        ↓
5. commit() quando houver alteração
        ↓
6. Recuperar resultados
        ↓
7. Fechar cursor
        ↓
8. Fechar conexão

## Principais comandos que utilizamos

| Python              | Função                    |
|---------------------|---------------------------|
| `sqlite3.connect()` | Cria a conexão            |
| `conexao.cursor()`  | Cria o cursor             |
| `cursor.execute()`  | Executa SQL               |
| `conexao.commit()`  | Salva as alterações       |
| `cursor.fetchall()` | Recupera os registros     |
| `cursor.close()`    | Fecha o cursor            |
| `conexao.close()`   | Fecha a conexão           |

## Por que usamos `commit()`?

O `commit()` é utilizado para **confirmar e salvar alterações no banco de dados**.

Comandos de consulta, como SELECT, não alteram os dados, por isso não usam commit.

Por exemplo, quando usamos:

- `INSERT` → inserir dados
- `UPDATE` → alterar dados
- `DELETE` → excluir dados
- `CREATE TABLE` → criar uma tabela

é comum utilizar:

```python
conexao.commit()

cursor.execute()
       ↓
Executa a alteração
       ↓
conexao.commit()
       ↓
Confirma e salva a alteração

## Por que usar `commit()`?

Comandos como `INSERT`, `UPDATE` e `DELETE` modificam os dados.

O `commit()` confirma essas alterações na transação.

```python
cursor.execute("UPDATE produtos SET preco = 100 WHERE id = 2")

conexao.commit()

Importante: o commit() não serve para "fazer o SQL funcionar".
Ele serve para confirmar as alterações realizadas na transação.

O comando COMMIT não é necessário na maioria das vezes no SQLite, pois ele opera por padrão no modo de confirmação automática (auto-commit). Cada comando que altera dados é salvo de forma imediata e individual, exceto quando você inicia uma transação de forma manual.


#### Quando o COMMIT não é necessário:
# Linha de comando padrão (CLI): Quando você usa o terminal do SQLite e digita um INSERT, UPDATE ou DELETE, a alteração vai para o arquivo de forma instantânea.
# Consultas de leitura (SELECT): Nunca precisam de salvamento ou confirmação.
# Comandos isolados: Se nenhuma transação foi aberta com BEGIN ou BEGIN TRANSACTION, o SQLite assume um auto-commit para cada instrução.

---

# Python + SQL com Pandas

Até agora utilizamos o `sqlite3` diretamente.

Isso funciona, mas precisamos escrever várias etapas:

```text
Conexão
   ↓
Cursor
   ↓
SQL
   ↓
execute()
   ↓
fetchall()
   ↓
Transformar resultado

Com o Pandas, muitas dessas tarefas ficam mais simples.

Podemos trabalhar com os dados diretamente em um DataFrame.

O Pandas também permite:
 - Ler dados do banco para um DataFrame
 - Executar SQL
 - Gravar DataFrames no banco
 - Trabalhar com os dados utilizando as ferramentas do Pandas


### Exemplo executável

```python
import pandas as pd
import sqlite3

In [12]:
import pandas as pd
import sqlite3

conexao = sqlite3.connect("dados/loja.db")

In [13]:
df = pd.read_sql("SELECT * FROM produtos", conexao)

df

   id      nome   preco
0   1  Notebook  3500.0
1   3   Teclado   150.0

Inserindo dados com Pandas

Também podemos criar um DataFrame:

In [14]:
novos_produtos = pd.DataFrame({
    "id": [4, 5],
    "nome": ["Monitor", "Webcam"],
    "preco": [1200, 300]
})

novos_produtos

   id     nome  preco
0   4  Monitor   1200
1   5   Webcam    300

In [15]:
novos_produtos.to_sql(
    "produtos",
    conexao,
    if_exists="append",
    index=False
)

2

In [16]:
df = pd.read_sql("SELECT * FROM produtos", conexao)

df

   id      nome   preco
0   1  Notebook  3500.0
1   3   Teclado   150.0
2   4   Monitor  1200.0
3   5    Webcam   300.0

Fechando a conexão

Mesmo utilizando Pandas, quando criamos uma conexão manualmente, continuamos responsáveis por fechá-la:

In [17]:
conexao.close()

### `if_exists` no `to_sql()`

O parâmetro `if_exists` define o que o Pandas deve fazer caso a tabela já exista no banco.

- **`"append"`** → adiciona os novos dados à tabela existente.
- **`"replace"`** → apaga a tabela existente e cria uma nova com os dados do DataFrame.
- **`"fail"`** → gera um erro caso a tabela já exista.

Exemplo:

```python
df.to_sql("produtos", conexao, if_exists="append", index=False)